In [18]:
import numpy as np

# Funzione helper per rendere l'output in console pulito e leggibile
def stampa_intestazione(titolo):
    print("\n" + "=" * 60)
    print(f"=== {titolo} ===")
    print("=" * 60)

# --- DATI DI PARTENZA ---
# Corretto l'errore di sintassi nell'ultimo elemento (77,8 -> 77.8)
pesi = np.array([82.5, 74.0, 91.0, 68.3, 77.8])
bpm = np.array([145, 162, 138, 171, 155])

calorie = np.array([
    [1800, 2100, 1950, 2200],
    [1500, 1700, 1600, 1900],
    [2300, 2500, 2400, 2600],
    [1200, 1400, 1300, 1500],
    [2000, 1900, 2100, 2050],
])

# --- PUNTO 1: ISPEZIONE DELLE PROPRIETÀ ---
stampa_intestazione("Punto 1: Ispezione delle proprietà del 1° array (pesi)")
print(f"Tipo elementi (dtype)   : {pesi.dtype}")
print(f"Forma (shape)           : {pesi.shape}")
print(f"N dimensioni (ndim)     : {pesi.ndim}")
print(f"N totale elementi       : {pesi.size}")
print(f"Memoria occupata        : {pesi.nbytes} bytes")

# --- PUNTO 2: MATRICE 2D E SLICING ---
stampa_intestazione("Punto 2: Matrice 2D delle calorie e Slicing")
print(f"Shape della matrice calorie   : {calorie.shape}")
print(f"Ndim della matrice calorie    : {calorie.ndim}")

stampa_intestazione("Punto 2: Estrazione singola riga")
riga_atleta1 = calorie[0, :]
print(f"Calorie del primo atleta: {riga_atleta1}")

stampa_intestazione("Punto 2: Estrazione singola colonna")
colonna_mese_2 = calorie[:, 1]
print(f"Calorie di tutti gli atleti del mese 2: {colonna_mese_2}")

stampa_intestazione("Punto 2: Estrazione sottomatrice")
sottomatrice = calorie[0:3, 0:2]
print(f"Sottomatrice (primi 3 atleti, primi 2 mesi):\n{sottomatrice}")

# --- PUNTO 3: OPERAZIONI VETTORIALI ---
stampa_intestazione("Punto 3: Operazioni vettoriali")

# Calorie totali per atleta
calorie_totali = np.sum(calorie, axis=1)
print(f"Calorie totali per atleta:           {calorie_totali}")

# Media mensile di calorie bruciate dalla palestra
media_mensile_palestra = np.mean(calorie, axis=0)
print(f"Media calorie bruciate nei 4 mesi:    {np.round(media_mensile_palestra)}")

# --- PUNTO 4: SIMULAZIONE ---
stampa_intestazione("Punto 4: Simulazione di 1 milione di frequenze cardiache")

numero_simulazioni = 1_000_000
# Corretto .radiant in .randint
dati_cardiaci = np.random.randint(60, 180, size=numero_simulazioni)

print(f"Simulazione completata con successo!")
print(f"Generati {dati_cardiaci.size:,} dati cardiaci (Range: 60-180 BPM).")
print(f"Primi 10 valori simulati: {dati_cardiaci[:10]}")


=== Punto 1: Ispezione delle proprietà del 1° array (pesi) ===
Tipo elementi (dtype)   : float64
Forma (shape)           : (5,)
N dimensioni (ndim)     : 1
N totale elementi       : 5
Memoria occupata        : 40 bytes

=== Punto 2: Matrice 2D delle calorie e Slicing ===
Shape della matrice calorie   : (5, 4)
Ndim della matrice calorie    : 2

=== Punto 2: Estrazione singola riga ===
Calorie del primo atleta: [1800 2100 1950 2200]

=== Punto 2: Estrazione singola colonna ===
Calorie di tutti gli atleti del mese 2: [2100 1700 2500 1400 1900]

=== Punto 2: Estrazione sottomatrice ===
Sottomatrice (primi 3 atleti, primi 2 mesi):
[[1800 2100]
 [1500 1700]
 [2300 2500]]

=== Punto 3: Operazioni vettoriali ===
Calorie totali per atleta:           [8050 6700 9800 5400 8050]
Media calorie bruciate nei 4 mesi:    [1760. 1920. 1870. 2050.]

=== Punto 4: Simulazione di 1 milione di frequenze cardiache ===
Simulazione completata con successo!
Generati 1,000,000 dati cardiaci (Range: 60-180 BPM).


In [26]:
import numpy as np

altezze = np.array([170, 165, 180, 155, 175, 160, 190, 168, 172, 158])

pesi = np.array([70, 58, 85, 52, 78, 65, 95, 72, 68, 55])

pressione = np.array([120, 118, 125, 115, 122, 119, 128, 121, 195, 116])

dati = np.column_stack([altezze, pesi, pressione])


print("--- PUNTO 1 ---")
print("Matrice dati (10x3):\n", dati)
print("Shape:", dati.shape)
print("Dtype:", dati.dtype)
print("\n" + "-"*40 + "\n")


# Standardizzazione con Z-score

dati_standardizzati = np.zeros_like(dati, dtype=float)

numero_colonne = dati.shape[1]
for i in range(numero_colonne):
    colonna = dati[:, 1]
    media_colonna = np.mean(colonna)
    deviazione_standard_colonna = np.std(colonna)

    dati_standardizzati[:, i] = (colonna - media_colonna) / deviazione_standard_colonna

media_verificata =  np.mean(dati_standardizzati, axis=0)
deviazione_standard_verifca = np.std(dati_standardizzati, axis=0)


print("--- PUNTO 2 ---")
print("Matrice standardizzata:\n", dati_standardizzati)
print("Verifica Medie (circa 0):", np.round(media_verificata, 2))
print("Verifica Deviazioni Standard (circa 1):", np.round(deviazione_standard_verifca, 2))
print("\n" + "-"*40 + "\n")



# --- 3. Rileva outlier: IQR ---

Q1 = np.percentile(dati, 25, axis=0)
Q3 = np.percentile(dati, 75, axis=0)
IQR = Q3 - Q1

limite_inferiore = Q1 - 1.5 * IQR
limite_superiore = Q3 + 1.5 * IQR

# Individua i pazienti che hanno almeno una misurazione fuori dai limiti
outliers = np.any((dati < limite_inferiore) | (dati > limite_superiore), axis=1)

print("--- PUNTO 3 ---")
print("Q1 per colonna:", Q1)
print("Q3 per colonna:", Q3)
print("IQR per colonna:", IQR)
print("Pazienti outlier (True indica che è un outlier):", outliers)
print("\n" + "-"*40 + "\n")



# --- 4. Calcola la matrice di covarianza ---

matrice_cov = np.cov(dati_standardizzati, rowvar=False)

print("--- PUNTO 4 ---")
print("Matrice di covarianza (sui dati standardizzati):\n", matrice_cov)
print("\n" + "-"*40 + "\n")

--- PUNTO 1 ---
Matrice dati (10x3):
 [[170  70 120]
 [165  58 118]
 [180  85 125]
 [155  52 115]
 [175  78 122]
 [160  65 119]
 [190  95 128]
 [168  72 121]
 [172  68 195]
 [158  55 116]]
Shape: (10, 3)
Dtype: int64

----------------------------------------

--- PUNTO 2 ---
Matrice standardizzata:
 [[ 0.01561928  0.01561928  0.01561928]
 [-0.92153758 -0.92153758 -0.92153758]
 [ 1.18706536  1.18706536  1.18706536]
 [-1.39011602 -1.39011602 -1.39011602]
 [ 0.64039052  0.64039052  0.64039052]
 [-0.37486275 -0.37486275 -0.37486275]
 [ 1.96802942  1.96802942  1.96802942]
 [ 0.17181209  0.17181209  0.17181209]
 [-0.14057353 -0.14057353 -0.14057353]
 [-1.1558268  -1.1558268  -1.1558268 ]]
Verifica Medie (circa 0): [0. 0. 0.]
Verifica Deviazioni Standard (circa 1): [1. 1. 1.]

----------------------------------------

--- PUNTO 3 ---
Q1 per colonna: [161.25  59.75 118.25]
Q3 per colonna: [174.25  76.5  124.25]
IQR per colonna: [13.   16.75  6.  ]
Pazienti outlier (True indica che è un outlier

In [ ]:
# Array di riferimento

a = np.array([3, 7, 1, 9, 4, 2, 8, 5, 10])
m = np.array([1, 2, 3], [4, 5,  6], [7, 8, 9], dtype=float)

stipendi = np.array([2000, 2500, 3000, 3500, 4000])