In [4]:
import numpy as np
atleti = [
    "Marco",
    "Luca",
    "Sara",
    "Paolo",
    "Anna",
    "Giulia"
]

altezza = [182, 175, 168, 160, 185, 165]
peso = [82, 76, 60, 55, 88, 58]
torace = [102, 98, 85, 80, 106, 83]
coscia = [61, 58, 50, 48, 65, 49]
imc = [24.8, 24.8, 21.3, 21.5, 25.7, 21.3]



# calcolare la media di una variabile
def calcola_media(lista):
    return sum(lista) / len(lista)


# calcolare la deviazion standard campionaria

def calcola_deviazione_standard(lista, media):
    varianza = sum((x - media) ** 2 for x in lista) / (len(lista) - 1)
    return varianza ** 0.5

# standardizza le variabili tarmite z-score 

def standardizza(lista):
    media = calcola_media(lista)
    dev_std = calcola_deviazione_standard(lista, media)
    return [(x - media) / dev_std for x in lista]

# calcolo covarianza

def calcola_covarianza(x, y):
    n = len(x)
    media_x = calcola_media(x)
    media_y = calcola_media(y)
    
    somma_prodotti = 0
    for i in range(n):
        somma_prodotti += (x[i] - media_x) * (y[i] - media_y)
        
    return somma_prodotti / (n - 1)


# 3. CREAZIONE DATI STANDARDIZZATI (Z-SCORE)
altezza_z = standardizza(altezza)
peso_z = standardizza(peso)
torace_z = standardizza(torace)
coscia_z = standardizza(coscia)
imc_z = standardizza(imc)

dati_z = [
    altezza_z,
    peso_z, 
    torace_z,
    coscia_z, 
    imc_z 
]

# Nomi delle variabili (con le virgole!)
nomi_variabili = [
    "altezza",
    "peso",
    "torace",
    "coscia",
    "imc"
]

n_var = len(dati_z)


# creazione matrice di covarianza

matrice_cov = []

for i in range(n_var):
    riga = []
    for j in range(n_var):
        cov = calcola_covarianza(dati_z[i], dati_z[j])
        riga.append(round(cov, 4))
    matrice_cov.append(riga)

# calcolare utovalori e autovettori

cov_np = np.array(matrice_cov)
print(cov_np)

# Autovalori e Autovettori

autovalori, autovettori = np.linalg.eig(cov_np)
print("AutoValori\n")

for i, valore in enumerate(autovalori):
    print(f"PC{i+1}: {valore:.2f}")
    

print("AutoVettori\n")

for i in range(len(autovalori)):
    print(f"\nPC{i+1}")

    for nome, coeff in zip(nomi_variabili, autovettori[:, i]):
        print(f"{nome:10} {coeff:.2f}")




[[1.     0.9844 0.985  0.9794 0.9255]
 [0.9844 1.     0.9986 0.9985 0.9765]
 [0.985  0.9986 1.     0.9947 0.9765]
 [0.9794 0.9985 0.9947 1.     0.9756]
 [0.9255 0.9765 0.9765 0.9756 1.    ]]
AutoValori

PC1: 4.92+0.00j
PC2: 0.07+0.00j
PC3: 0.01+0.00j
PC4: -0.00+0.00j
PC5: 0.00+0.00j
AutoVettori


PC1
altezza    0.44+0.00j
peso       0.45+0.00j
torace     0.45+0.00j
coscia     0.45+0.00j
imc        0.44+0.00j

PC2
altezza    -0.67+0.00j
peso       -0.04+0.00j
torace     -0.04+0.00j
coscia     0.00+0.00j
imc        0.74+0.00j

PC3
altezza    0.25+0.00j
peso       -0.16+0.00j
torace     0.46+0.00j
coscia     -0.80+0.00j
imc        0.25+0.00j

PC4
altezza    0.48+0.00j
peso       -0.68+0.00j
torace     -0.35+0.00j
coscia     0.20+0.00j
imc        0.38+0.00j

PC5
altezza    -0.26+0.00j
peso       -0.55+0.00j
torace     0.68+0.00j
coscia     0.34+0.00j
imc        -0.22+0.00j


## Esercizio 2

In [ ]:
import numpy as np
aziende = [
    "A",
    "B",
    "C",
    "D",
    "E",
    "F",
    "G",
    "H"
]

fatturato = [1000, 900, 850, 750, 300, 350, 450, 500]
dipendenti = [250, 220, 210, 180, 70, 80, 100, 120]
patrimonio = [1200, 1100, 1050, 900, 400, 450, 550, 650]
margine = [10, 12, 28, 30, 8, 10, 25, 27]
soddisfazioni = [55, 60, 90, 95, 50, 55, 88, 92]



# calcolare la media di una variabile
def calcola_media(lista):
    return sum(lista) / len(lista)


# calcolare la deviazion standard campionaria

def calcola_deviazione_standard(lista, media):
    varianza = sum((x - media) ** 2 for x in lista) / (len(lista) - 1)
    return varianza ** 0.5

# standardizza le variabili tarmite z-score 

def standardizza(lista):
    media = calcola_media(lista)
    dev_std = calcola_deviazione_standard(lista, media)
    return [(x - media) / dev_std for x in lista]

# calcolo covarianza

def calcola_covarianza(x, y):
    n = len(x)
    media_x = calcola_media(x)
    media_y = calcola_media(y)
    
    somma_prodotti = 0
    for i in range(n):
        somma_prodotti += (x[i] - media_x) * (y[i] - media_y)
        
    return somma_prodotti / (n - 1)


# 3. CREAZIONE DATI STANDARDIZZATI (Z-SCORE)
fatturato_z = standardizza(fatturato)
dipendenti_z = standardizza(dipendenti)
patrimonio_z = standardizza(patrimonio)
margine_z = standardizza(margine)
soddisfazioni_z = standardizza(soddisfazioni)

dati_z = [
    fatturato_z,
    dipendenti_z, 
    patrimonio_z,
    margine_z, 
    soddisfazioni_z 
]

# Nomi delle variabili (con le virgole!)
nomi_variabili = [
    "fatturato",
    "dipendenti",
    "patrimonio",
    "margine",
    "soddisfazioni"
]

n_var = len(dati_z)


# creazione matrice di covarianza

matrice_cov = []

for i in range(n_var):
    riga = []
    for j in range(n_var):
        cov = calcola_covarianza(dati_z[i], dati_z[j])
        riga.append(round(cov, 4))
    matrice_cov.append(riga)

# calcolare utovalori e autovettori

cov_np = np.array(matrice_cov)
print(cov_np)

# Autovalori e Autovettori

autovalori, autovettori = np.linalg.eig(cov_np)
print("AutoValori\n")

for i, valore in enumerate(autovalori):
    print(f"PC{i+1}: {valore:.2f}")
    

print("AutoVettori\n")

for i in range(len(autovalori)):
    print(f"\nPC{i+1}")

    for nome, coeff in zip(nomi_variabili, autovettori[:, i]):
        print(f"{nome:10} {coeff:.2f}")


[[1.     0.9991 0.9988 0.1184 0.0987]
 [0.9991 1.     0.9992 0.0986 0.0778]
 [0.9988 0.9992 1.     0.1185 0.0988]
 [0.1184 0.0986 0.1185 1.     0.9971]
 [0.0987 0.0778 0.0988 0.9971 1.    ]]
AutoValori

PC1: 3.06+0.00j
PC2: 1.94+0.00j
PC3: 0.00+0.00j
PC4: 0.00+0.00j
PC5: 0.00+0.00j
AutoVettori


PC1
fatturato  -0.56+0.00j
dipendenti -0.56+0.00j
patrimonio -0.56+0.00j
margine    -0.17+0.00j
soddisfazioni -0.16+0.00j

PC2
fatturato  -0.13+0.00j
dipendenti -0.14+0.00j
patrimonio -0.13+0.00j
margine    0.69+0.00j
soddisfazioni 0.69+0.00j

PC3
fatturato  0.35+0.00j
dipendenti -0.79+0.00j
patrimonio 0.44+0.00j
margine    0.17+0.00j
soddisfazioni -0.18+0.00j

PC4
fatturato  0.73+0.00j
dipendenti -0.05+0.00j
patrimonio -0.68+0.00j
margine    0.02+0.00j
soddisfazioni -0.02+0.00j

PC5
fatturato  0.11+0.00j
dipendenti -0.20+0.00j
patrimonio 0.10+0.00j
margine    -0.69+0.00j
soddisfazioni 0.68+0.00j
