In [4]:
import numpy as np


def imc(x, y):
    return y / ((x / 100) ** 2)

altezze_cm = np.array([170, 180, 165, 155, 175, 160, 190, 168, 172, 158])
pesi_kg = np.array([70, 58, 85, 52, 78, 65, 95, 72, 68, 55])
imc = imc(altezze_cm, pesi_kg)
id_pazienti = np.arange(1, 11)
i = np.eye(3,3)
zeros = np.zeros(5)

print(f"ID:         {id_pazienti}")
print(f"Altezze:         {altezze_cm}")
print(f"Pesi:         {pesi_kg}")
print(f"IMC:         {np.round(imc, 2)}")


print("\n", i)
print(zeros)




ID:         [ 1  2  3  4  5  6  7  8  9 10]
Altezze:         [170 180 165 155 175 160 190 168 172 158]
Pesi:         [70 58 85 52 78 65 95 72 68 55]
IMC:         [24.22 17.9  31.22 21.64 25.47 25.39 26.32 25.51 22.99 22.03]

 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[0. 0. 0. 0. 0.]
