In [3]:
import time 

n = 1_000_000
lista_a = list(range(n))
lista_b = list(range(n))

start = time.time()
risultato_lista = [a + b for a, b in zip(lista_a, lista_b)]
tempo_lista = time.time() - start


In [4]:
import time
import numpy as np

n = 1_000_000
array_a = np.arange(n)
array_b = np.arange(n)

start = time.time()
risultato_numpy = array_a + array_b
tempo_numpy = time.time() - start 

print(f"tempo senza numpy {tempo_lista}")
print(f"tempo con numpy {tempo_numpy}")
print(f"Numpy è : {tempo_lista - tempo_numpy} secondi più veloce")



tempo senza numpy 0.09510564804077148
tempo con numpy 0.005118608474731445
Numpy è : 0.08998703956604004 secondi più veloce


In [5]:
import numpy as np
lista_mista = [1, "ciao", 3.5, True]
array_numeri = np.array([1, 2, 3, 4])

print(f"Lista Python        : {lista_mista}")
print(f"Array Numpy         : {array_numeri}")
print()

print(f"Tipo elementi (dtype)   : {array_numeri.dtype}")
print(f"Forma (shape)           : {array_numeri.shape}")
print(f"N dimensioni (ndim)     : {array_numeri.ndim}")
print(f"N totale elementi       : {array_numeri.size}")
print(f"Memoria occpuata        : {array_numeri.nbytes} bytes")

Lista Python        : [1, 'ciao', 3.5, True]
Array Numpy         : [1 2 3 4]

Tipo elementi (dtype)   : int64
Forma (shape)           : (4,)
N dimensioni (ndim)     : 1
N totale elementi       : 4
Memoria occpuata        : 32 bytes


## Operazioni Vettroaili

#### creazione della lista

In [6]:
a1 = np.array([10, 20, 30, 40, 50])
print(a1)

[10 20 30 40 50]


### Arange

In [7]:
a2 = np.arange(0, 10, 2)
print(a2)

[0 2 4 6 8]


### Linspace:

In [8]:
a3 = np.linspace(0, 1, 5)
print(a3)

[0.   0.25 0.5  0.75 1.  ]


### Array di zeri

In [9]:
a4 = np.zeros(5)
print(a4)

[0. 0. 0. 0. 0.]


### Matrice di 1

In [10]:
a5 = np.ones((2, 3))
print(a5)

[[1. 1. 1.]
 [1. 1. 1.]]


### Matrice d'identità

In [11]:
e = np.eye(3)
print(e)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


### Numeri casuali unformi

In [12]:
r = np.random.rand(3,3)
print(r)

[[0.83305209 0.38112287 0.17358789]
 [0.67955932 0.06043061 0.67677594]
 [0.33139824 0.68495301 0.65967668]]


### Caasuali normali

In [14]:
z = np.zeros(5)
print(z)

[0. 0. 0. 0. 0.]


# Array

## Operazioni con gli Array

In [15]:
import numpy as np

stipendi = np.array([2000, 2500, 3000, 3500, 4000])

## Operazioni statistiche fondamentali

In [16]:
dati = np.array([15, 22, 18, 30, 25, 19, 28, 22, 17, 26])

print("=== STATISTICHE ARRAY ===")
print(f"Media         : {np.mean(dati):.2f}")
print(f"Mediana       : {np.median(dati):.2f}")
print(f"Dev. standard : {np.std(dati):.2f}")
print(f"Varianza      : {np.var(dati):.2f}")
print(f"Minimo        : {np.min(dati)} (indice: {np.argmin(dati)})")
print(f"Massimo       : {np.max(dati)} (indice: {np.argmax(dati)})")
print(f"Somma         : {np.sum(dati)}")
print(f"Percentile 25 : {np.percentile(dati, 25)}")
print(f"Percentile 75 : {np.percentile(dati, 75)}")
print(f"IQR           : {np.percentile(dati, 75) - np.percentile(dati, 25)}")

=== STATISTICHE ARRAY ===
Media         : 22.20
Mediana       : 22.00
Dev. standard : 4.73
Varianza      : 22.36
Minimo        : 15 (indice: 0)
Massimo       : 30 (indice: 3)
Somma         : 222
Percentile 25 : 18.25
Percentile 75 : 25.75
IQR           : 7.5


## Index Slicing

In [17]:
a = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 100])

print(f"Primo elemento    : {a[0]}")
print(f"Ultimo elemento   : {a[-1]}")
print(f"Terzo elemento    : {a[2]}")

# Slicing [start:stop:step]
print(f"Primi 4           : {a[:4]}")
print(f"Ultimi 3          : {a[-3:]}")
print(f"Dal 2° al 7°      : {a[1:7]}")
print(f"Step 2            : {a[::2]}")
print(f"Invertito         : {a[::-1]}")

# Boolean indexing
filtro = a > 50
print(f"\nMask booleana     : {filtro}")
print(f"Valori > 50       : {a[filtro]}")

Primo elemento    : 10
Ultimo elemento   : 100
Terzo elemento    : 30
Primi 4           : [10 20 30 40]
Ultimi 3          : [ 80  90 100]
Dal 2° al 7°      : [20 30 40 50 60 70]
Step 2            : [10 30 50 70 90]
Invertito         : [100  90  80  70  60  50  40  30  20  10]

Mask booleana     : [False False False False False  True  True  True  True  True]
Valori > 50       : [ 60  70  80  90 100]


## Array Multidimensionali

In [21]:
M = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12]
])

print(f"Shape   :{M.shape}")
print(f"ndim    :{M.ndim}")
print(f"size    :{M.size}")


print(f"\nElemento  [0,0]     = {M[0,0]}")
print(f"Elemento    [1, 2]    = {M[1, 2]}") 
print(f"Elemento    [2, -1]   = {M[2, -1]}")

# selezione di righe e colonne

print(f"\nPrima riga    :{M[0, :]}")
print(f"Terza colonna   :{M[:, 2]}")
print(f"Sottomatrice    :{M[0:2, 1:3]}")


# Operazioni su assi

print(f"\nSomma colonne (axis=0)    : {M.sum(axis=0)}")
print(f"\nSomma righe (axis=1)      : {M.sum(axis=1)}")
print(f"\nMedia Globale             : {M.mean():.2f}")


Shape   :(3, 4)
ndim    :2
size    :12

Elemento  [0,0]     = 1
Elemento    [1, 2]    = 7
Elemento    [2, -1]   = 12

Prima riga    :[1 2 3 4]
Terza colonna   :[ 3  7 11]
Sottomatrice    :[[2 3]
 [6 7]]

Somma colonne (axis=0)    : [15 18 21 24]

Somma righe (axis=1)      : [10 26 42]

Media Globale             : 6.50


## Somma colonne

In [22]:
print(f"\nSomma colonne (axis=0)    : {M.sum(axis=0)}")


Somma colonne (axis=0)    : [15 18 21 24]


## Somma righe

In [23]:
print(f"\nSomma righe (axis=1)      : {M.sum(axis=1)}")


Somma righe (axis=1)      : [10 26 42]


# np.linal.eig

In [ ]:
autovalori = [2.2479, 0.0361, 1.0493]

# DataFrame

In [ ]:
import pandas as pd
import numpy  as np
data = {
    "nome":      ["Anna", "Luca",    "Marco",   "Sara",  "Giulia"],
    "eta":       [25,       32,        28,        45,       35   ],
    "città":     ["Roma", "Milano", "Roma", "Torino", "Milano"   ],
    "stipendio": [2000,    3500,     2800,    5000,     4200     ],
    "anni_expo": [2,        8,         4,       18,       10     ]
}

df = pd.DataFrame(data)
df.head()

,nome,eta,città,stipendio,anni_expo
0,Anna,25,Roma,2000,2
1,Luca,32,Milano,3500,8
2,Marco,28,Roma,2800,4
3,Sara,45,Torino,5000,18
4,Giulia,35,Milano,4200,10


: 