In [2]:
import time 

n = 1_000_000
lista_a = list(range(n))
lista_b = list(range(n))

start = time.time()
risultato_lista = [a + b for a, b in zip(lista_a, lista_b)]
tempo_lista = time.time() - start


In [3]:
import time
import numpy as np

n = 1_000_000
array_a = np.arange(n)
array_b = np.arange(n)

start = time.time()
risultato_numpy = array_a + array_b
tempo_numpy = time.time() - start 

print(f"tempo senza numpy {tempo_lista}")
print(f"tempo con numpy {tempo_numpy}")
print(f"Numpy è : {tempo_lista - tempo_numpy} secondi più veloce")



tempo senza numpy 0.05481314659118652
tempo con numpy 0.002560138702392578
Numpy è : 0.052253007888793945 secondi più veloce


In [4]:
import numpy as np
lista_mista = [1, "ciao", 3.5, True]
array_numeri = np.array([1, 2, 3, 4])

print(f"Lista Python        : {lista_mista}")
print(f"Array Numpy         : {array_numeri}")
print()

print(f"Tipo elementi (dtype)   : {array_numeri.dtype}")
print(f"Forma (shape)           : {array_numeri.shape}")
print(f"N dimensioni (ndim)     : {array_numeri.ndim}")
print(f"N totale elementi       : {array_numeri.size}")
print(f"Memoria occpuata        : {array_numeri.nbytes} bytes")

Lista Python        : [1, 'ciao', 3.5, True]
Array Numpy         : [1 2 3 4]

Tipo elementi (dtype)   : int64
Forma (shape)           : (4,)
N dimensioni (ndim)     : 1
N totale elementi       : 4
Memoria occpuata        : 32 bytes


## Operazioni Vettroaili

#### creazione della lista

In [12]:
a1 = np.array([10, 20, 30, 40, 50])
print(a1)

[10 20 30 40 50]


### Arange

In [13]:
a2 = np.arange(0, 10, 2)
print(a2)

[0 2 4 6 8]


### Linspace:

In [14]:
a3 = np.linspace(0, 1, 5)
print(a3)

[0.   0.25 0.5  0.75 1.  ]


### Array di zeri

In [15]:
a4 = np.zeros(5)
print(a4)

[0. 0. 0. 0. 0.]


### Matrice di 1

In [16]:
a5 = np.ones((2, 3))
print(a5)

[[1. 1. 1.]
 [1. 1. 1.]]


### Matrice d'identità

In [ ]:
e = np.eye(3)
print(e)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


### Numeri casuali unformi

In [18]:
r = np.random.rand(3,3)
print(r)

[[0.38572726 0.82612929 0.13564074]
 [0.99692288 0.13664741 0.37557654]
 [0.47255746 0.81060963 0.84644839]]


### Caasuali normali

In [20]:
z = np.zeros(5)
print(z)

[0. 0. 0. 0. 0.]


## Operazioni con gli Array

In [ ]:
import numpy as np

stipendi = np.array([2000, 2500, 3000, 3500, 4000])

